### ISSUE TITLE
Error when run the appyter using some default inputs

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/KinomeScan-Appyter#9]
When the appyter is run using the following inputs, all provided as example inputs within the "?" text:

Input a Small Molecule and/or Kinase for KINOMEscan Data
Small molecule name: Afatinib
Kinase name: ABL2

Upload or Enter a Kinase List:
Input kinase list:
ABL2
ALK
CSF1R
EPHA3

Input a Small Molecule and/or Kinase for TAS Data
Small molecule name: Afatinib
Kinase name: ABL2

... the appyter runs through In [7], but generates the error message shown in the attached screenshot ("NameError: name 'percentage_list' is not defined") at the In [8] section, and at the top of the notebook, the error message "Error: Cell execution error on cell 11" is displayed.

![KINOMEscanAndTAS_Appyter_ErrorMessage_7-12-20](https://user-images.githubusercontent.com/7283504/87272131-5a2f8b00-c4a3-11ea-8d4f-239472376174.PNG)

**Comment by serena-zhang** [comment]
Fixed, thank you so much for pointing this out @KMJ1618 !
